### ISSUE TITLE
Bump json version

### ISSUE THREAD

**Issue by eos87** [quandl/quandl_client#11]
Hey guys,

are you merging with bump-json branch soon? This is kind of blocking other gems from updating because of json version :( If you could do it would be really appreciated.

Thanks

**Comment by mbasset** [comment]
Hi eos87. You could also try using our newer https://github.com/quandl/quandl-ruby package. This package is currently deprecated.

**Comment by eos87** [comment]
Ah great. Thanks. I'm closing this :)
